### ISSUE TITLE
Add Internal Documentation (PHPDocs) Roadmap

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#29]
## Abstract
Before releasing v1 I want all the code to be documented with PHPDocs. This issue will serve as the roadmap to track this sub-project.

### Classes missing class description

- [x] ConvertsArrayToFrontMatter
- [x] ConvertsFooterMarkdown
- [x] CreatesDefaultDirectories
- [x] CreatesNewMarkdownPostFile
- [x] **GeneratesDocumentationSidebar:** Create the sidebar items for the documentation page.
- [x] **GeneratesNavigationMenu:** Generate the dynamic navigation menu.
- [x] **MarkdownConverter:** Converts Markdown into HTML.
- [x] BuildStaticSiteCommand
- [x] Debug
- [x] **HydePublishConfigsCommand:** Publish the Hyde Config Files.
- [x] **HydePublishHomepageCommand:** Publish one of the default homepages.
- [x] **HydePublishViewsCommand:** Publish the Hyde assets.
- [x] MakePostCommand
- [x] MakeValidatorCommand
- [x] PublishStubsCommand
- [x] Validate
- [x] **DocumentationPageParser:** Parses a Documentation file into an object.
- [x] **Features:** Allows features to be enabled and disabled in a simple object-oriented manner.
- [x] HomeServiceProvider
- [x] **Hyde:** General interface for Hyde services.
- [x] HydeServiceProvider
- [x] **MarkdownPageParser:** Parses a Markdown file into an object with support for Front Matter.
- [x] **MarkdownPostParser:** Parses a Markdown file into an object with support for Front Matter.
- [x] **Author:** The Post Author Object Model.
- [x] **BladePage:** A basic wrapper for the custom Blade View compiler.
- [x] **DocumentationPage:** A simple class that contains the content of a Documentation Page.
- [x] **MarkdownDocument:** Intermediate object model created by the MarkdownFileService and contains the Front Matter and Markdown body found in a document.
- [x] **MarkdownPage:** The basis for custom Markdown Pages.
- [x] **MarkdownPost:** The basis for Markdown Blog Posts.
- [x] **AuthorService:** Contains service methods relating to blog post authors.
- [x] **CollectionService:** Contains service methods to return helpful collections of arrays and lists.
- [x] **MarkdownFileService:** Prepares a Markdown file for further usage.
- [x] **StaticPageBuilder:** Generates a static HTML page and saves it.
