### ISSUE TITLE
v0.26.x "The Meta Update" Tracker

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#377]
Tracking issues for the upcoming metadata focused update

- [ ] https://github.com/hydephp/framework/issues/376
- [ ] https://github.com/hydephp/framework/issues/375
- [ ] https://github.com/hydephp/framework/issues/370

**Comment by caendesilva** [comment]
Release has been published.
