### ISSUE TITLE
Remove redundancy and merge Meta and Metadata models

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#384]
Three parts to this:

- [x] Add the page metadata as part of the $page property
- [x] Make sure there are no duplicates in blog post pages
- [x] Extract metadata helpers to concern
