### ISSUE TITLE
Upcoming release notes draft and checklist for v0.31.x

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#502]
# Feature/implementation tracker

Checklist:

- [x] Publish new HydeFront release with style changes
- [x] Update HydeFront asset version
- [ ] Add missing tests (if any)

--- 

# Release notes

### Markdown pre and post-processing
https://github.com/hydephp/framework/pull/488 adds a framework and a few implementations for Markdown postprocessing and preprocessing. Examples for these can be found in the Markdown documentation.

#### Colored blockquotes https://github.com/hydephp/framework/issues/484
This preprocessor adds colored blockquotes using an easy semantic syntax.

#### Automatic filepath label for codeblocks https://github.com/hydephp/framework/issues/487 (pre and post)

Write a comment with the filepath on the first line of a fenced Markdown code block, and it will be added as a label in the top right corner. Works both with and without Torchlight.

### Makes documentation pages smarter

Hyde is all about taking something simple, and making it special. The blog posts are a great example of this, where Hyde manages to extract and generate rich data from the Markdown. But the documentation pages (with the exception of the sidebar) have been a little... plain. None of the actual article content is really that semantic. This PR begins to fix that. It does this by splitting the rendered Markdown document into three semantic parts, header, main content, and footer. This provides hooks for injecting dynamic content, all while keeping the HTML logically structured.

#### Create automatic link to documentation source files

Now Hyde can automatically add links to documentation pages that takes the user to a GitHub page (or similar) to edit the page. This makes it great for open-source projects looking to allow others to contribute to the documentation in a quick and easy manner.

The feature is automatically enabled when you specify a base URL in the Docs configuration file. Hyde expects this to be a GitHub path, but it will probably work with other methods as well, if not, please send a PR and/or create an issue on the [GitHub repository](https://github.com/hydephp/framework)!
